name: Python CI with Executable Packaging

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: chess-env
        python-version: 3.10
        auto-activate-base: false

    - name: Install dependencies
      run: |
        conda install -c conda-forge pygame -y
        conda install -c conda-forge pyinstaller -y
        conda install -c conda-forge flake8 -y
        conda install -c conda-forge pytest -y

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      run: |
        pytest
      continue-on-error: false # Stops the workflow if tests fail

    - name: Build Executable with PyInstaller
      run: |
        pyinstaller --onefile main.py -n ChessGameExecutable

    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: chess-game-executable
        path: dist/ChessGameExecutable
